from datos.info_cartas import *


mazo_original = [
    carta_1_de_espada,
    carta_2_de_espada,
    carta_3_de_espada,
    carta_4_de_espada,
    carta_5_de_espada,
    carta_6_de_espada,
    carta_7_de_espada,
    carta_10_de_espada,
    carta_11_de_espada,
    carta_12_de_espada,
    carta_1_de_basto,
    carta_2_de_basto,
    carta_3_de_basto,
    carta_4_de_basto,
    carta_5_de_basto,
    carta_6_de_basto,
    carta_7_de_basto,
    carta_10_de_basto,
    carta_11_de_basto,
    carta_12_de_basto,
    carta_1_de_oro,
    carta_2_de_oro,
    carta_3_de_oro,
    carta_4_de_oro,
    carta_5_de_oro,
    carta_6_de_oro,
    carta_7_de_oro,
    carta_10_de_oro,
    carta_11_de_oro,
    carta_12_de_oro,
    carta_1_de_copa,
    carta_2_de_copa,
    carta_3_de_copa,
    carta_4_de_copa,
    carta_5_de_copa,
    carta_6_de_copa,
    carta_7_de_copa,
    carta_10_de_copa,
    carta_11_de_copa,
    carta_12_de_copa
    ]
